In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.Series(np.random.uniform(size =  9), index = [["a", "a", "a", "b", "b", "c", "c", "d", "d"],[1,2,3,1,3,1,2,2,3]])

In [4]:
data

a  1    0.109121
   2    0.140633
   3    0.492502
b  1    0.900518
   3    0.213044
c  1    0.201381
   2    0.976481
d  2    0.822274
   3    0.367384
dtype: float64

In [5]:
#multindex is its index

In [6]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [7]:
data["b"]

1    0.900518
3    0.213044
dtype: float64

In [8]:
data["b":"c"]

b  1    0.900518
   3    0.213044
c  1    0.201381
   2    0.976481
dtype: float64

In [9]:
data.loc[["b","c"]]

b  1    0.900518
   3    0.213044
c  1    0.201381
   2    0.976481
dtype: float64

In [10]:
#selection form INNER LEVEL

In [11]:
data.loc[:,2]

a    0.140633
c    0.976481
d    0.822274
dtype: float64

In [12]:
#to convert this multindex into dataframe we use unstack

In [13]:
data.unstack()

          1         2         3
a  0.109121  0.140633  0.492502
b  0.900518       NaN  0.213044
c  0.201381  0.976481       NaN
d       NaN  0.822274  0.367384

In [14]:
#the inverse of this is stack

In [15]:
data.unstack().stack()

a  1    0.109121
   2    0.140633
   3    0.492502
b  1    0.900518
   2         NaN
   3    0.213044
c  1    0.201381
   2    0.976481
   3         NaN
d  1         NaN
   2    0.822274
   3    0.367384
dtype: float64

In [16]:
dingo = pd.DataFrame(np.arange(12).reshape((4,3)), 
                     index = [["a", "a", "b", "b"], [1, 2, 1, 2]], columns=[["Ohio", "Ohio", "Colorado"],["Green", "Red", "Green"]])

In [17]:
dingo

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [18]:
dingo.stack()

           Ohio  Colorado
a 1 Green     0       2.0
    Red       1       NaN
  2 Green     3       5.0
    Red       4       NaN
b 1 Green     6       8.0
    Red       7       NaN
  2 Green     9      11.0
    Red      10       NaN

In [19]:
dingo.index.names = ["key1","key2"]

In [20]:
dingo.columns.names = ["state","color"]

In [21]:
dingo

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [22]:
dingo.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['key1', 'key2'])

In [23]:
dingo.index.nlevels

2

In [24]:
#shows how many levels an index has

In [25]:
dingo["Ohio"]

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [26]:
pd.MultiIndex.from_arrays(
    [["Ohio" ,"Ohio", "Colorado"], ["Green", "Red", "Green"]], names=["state", "color"])

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

In [27]:
dingo.swaplevel("key1","key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [28]:
dingo

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [29]:
dingo.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [30]:
dingo.sort_index(level = 0)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [31]:
dingo.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [32]:
dingo.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [33]:
dingo.T.groupby(level="color").sum().T

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

Indexing with a DataFrame’s columns

In [34]:
x = pd.DataFrame({"a": range(7), "b":range(7,0,-1), "c":["one", "one", "one", "two", "two","two", "two"], "d": [0,1,2,0,1,2,3]})

In [35]:
x

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [36]:
h = x.set_index(["a","c"])

In [37]:
h

       b  d
a c
0 one  7  0
1 one  6  1
2 one  5  2
3 two  4  0
4 two  3  1
5 two  2  2
6 two  1  3

In [38]:
x.set_index(["a","c"], drop = False)

       a  b    c  d
a c
0 one  0  7  one  0
1 one  1  6  one  1
2 one  2  5  one  2
3 two  3  4  two  0
4 two  4  3  two  1
5 two  5  2  two  2
6 two  6  1  two  3

In [39]:
h.reset_index()

   a    c  b  d
0  0  one  7  0
1  1  one  6  1
2  2  one  5  2
3  3  two  4  0
4  4  two  3  1
5  5  two  2  2
6  6  two  1  3

## Combining and Merging Datasets

In [40]:
#There are mainly three ways to combine data here and i will be describing them as we move further on this topic

** Database - Style DataFrame Joins

In [41]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
....:                     
"data1": pd.Series(range(7), dtype="Int64")})

In [42]:
df2 = pd.DataFrame({"key": ["a", "b", "d"],
....:                     
"data2": pd.Series(range(3), dtype="Int64")})

In [43]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [44]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [45]:
#example of many to one join because df1 has multiple rows labeled a and b whereas df2 has only one row for each value in key column 
pd.merge(df1,df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [46]:
#For merging/joining operations and combine datasets by linking rows using one/more keys we use  "pandas.merge" function

In [47]:
#Int 64 type for nullable integers
#also here its not specified which column to join on due to which pandas.merge used the overlapping names as keys by default

In [48]:
pd.merge(df1, df2, on = "key") #have confusion here !

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [49]:
#NOTE FOR confusion of on = "key"   :The on="key" parameter tells pandas which column to use as the joining condition — it must exist in both DataFrames

In [50]:
#the order of column output is unspecified in pandas.merge function

In [51]:
df3 = pd.DataFrame({"lkey": ["b","b", "a", "c", "a", "a", "b"], 
                    "data1":pd.Series(range(7), dtype="Int64")})

In [52]:
df4 = pd.DataFrame({"rkey": ["a","b","d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [53]:
pd.merge(df3,df4, left_on = "lkey", right_on = "rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [54]:
#here pd.merge(df3,df4) will give syntax error as there would be no common values to perform merge
#also "C" and "d" are missing because the result that we got above is the common set found in both the tables 
#and also because pandas.merge does an "inner" join

In [55]:
pd.merge(df1,df2, how="outer")

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [56]:
#using how  we told pandas to to combine the effect of both left and right joins

In [57]:
pd.merge(df1, df2, how="left")

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   c      3   <NA>
4   a      4      0
5   a      5      0
6   b      6      1

In [58]:
pd.merge(df1,df2, how ="right")

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   d   <NA>      2

In [59]:
#AND HENCE when we mix both then we get the first case :)

In [60]:
#many to many merges forms the cartesian product of the matching keys

In [61]:
df1 = pd.DataFrame({"key":["b", "b", "a", "c", "a", "b"],
....:                     
"data1": pd.Series(range(6), dtype="Int64")})

In [62]:
df2 = pd.DataFrame({"key": ["a","b","a","b","d"],
                    "data2": pd.Series(range(5), dtype = "Int64")})

In [63]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [64]:
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [65]:
pd.merge(df1,df2,how = "left", on="key")

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [66]:
#here joining condition is "Key" column and the method to do is left join

In [67]:
#now experimenting on right join 
pd.merge(df1, df2, how = "right", on= "key")

   key  data1  data2
0    a      2      0
1    a      4      0
2    b      0      1
3    b      1      1
4    b      5      1
5    a      2      2
6    a      4      2
7    b      0      3
8    b      1      3
9    b      5      3
10   d   <NA>      4

In [68]:
# #here c is missing but why? as Right Join means:

# Keep all rows from the right DataFrame (df2), and only matching rows from the left (df1). If no match, fill with NaN.
#(mtlb ki df2 ke saare rows honge and df1 ke only matching rows hone and if df1 ke rows nhi match kr rhe with df2 ke row se then it will be replaced with NaN

In [69]:
#merging with multiple keys

In [70]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
   ....:                      "key2": ["one", "two", "one"],
   ....:                      "lval": pd.Series([1, 2, 3], dtype='Int64')})

In [71]:
 right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
   ....:                       "key2": ["one", "one", "one", "two"],
   ....:                       "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})

In [72]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [73]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [74]:
pd.merge(left, right, on=["key1","key2"], how="outer")

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [75]:
#treatmetn of overlapping column names

In [76]:
pd.merge(left,right, on="key1")

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [77]:
# #pandas.merge has a suffixes option
# for specifying strings to append to overlapping names in the left and right DataFrame
# object

In [78]:
pd.merge(left, right, on="key1", suffixes=("_left", "_right"))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

**Merging On Index

In [79]:
l1 = pd.DataFrame({"key1":["a", "b", "a", "a", "b", "c"],
                   "value": pd.Series(range(6), dtype="Int64")})

In [80]:
r2 = pd.DataFrame({"group_val":[3.5, 7]}, index=["a", "b"])

In [81]:
l1

  key1  value
0    a      0
1    b      1
2    a      2
3    a      3
4    b      4
5    c      5

In [82]:
r2

   group_val
a        3.5
b        7.0

**Merging on Index

In [83]:
#if mergekeys are found in its index then 
#PASS: left_index= True, right_index= True  or both to incdicate that index should be used as merge key

In [84]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
....:                       
"value": pd.Series(range(6), dtype="Int64")})

In [85]:
right1 = pd.DataFrame({"group_val":[3.5, 7]}, index=["a", "b"])

In [86]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [87]:
right1

   group_val
a        3.5
b        7.0

In [88]:
pd.merge(left1, right1, left_on="key", right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [89]:
#left_on to use columns in left dataframe as join key

In [90]:
#now the default merge method is ot intersect so for joining:

In [91]:
pd.merge(left1, right1, left_on="key", right_index=True, how="outer")

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [92]:
#with hierarchically indexed data

In [93]:
lefth = pd.DataFrame({"key1": ["Ohio", "Ohio", "Ohio",
   ....:                                "Nevada", "Nevada"],
   ....:                       "key2": [2000, 2001, 2002, 2001, 2002],
   ....:                       "data": pd.Series(range(5), dtype="Int64")})

In [94]:
righth_index = pd.MultiIndex.from_arrays(
   ....:     [
   ....:         ["Nevada", "Nevada", "Ohio", "Ohio", "Ohio", "Ohio"],
   ....:         [2001, 2000, 2000, 2000, 2001, 2002]
   ....:     ]
   ....: )

In [95]:
righth = pd.DataFrame({"event1": pd.Series([0, 2, 4, 6, 8, 10], dtype="Int64",
   ....:                                            index=righth_index),
   ....:                        "event2": pd.Series([1, 3, 5, 7, 9, 11], dtype="Int64",
   ....:                                            index=righth_index)})

In [96]:
lefth

     key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [97]:
righth

             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [98]:
righth_index

MultiIndex([('Nevada', 2001),
            ('Nevada', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2001),
            (  'Ohio', 2002)],
           )

In [99]:
pd.merge(lefth,righth, left_on=["key1", "key2"], right_index=True)

     key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
3  Nevada  2001     3       0       1
2    Ohio  2002     2      10      11

In [100]:
#indicate multiple columns to merge on as a list

In [101]:
pd.merge(lefth, righth, left_on=["key1", "key2"],
   ....:          right_index=True, how="outer")

     key1  key2  data  event1  event2
4  Nevada  2000  <NA>       2       3
3  Nevada  2001     3       0       1
4  Nevada  2002     4    <NA>    <NA>
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11

In [102]:
 left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
   ....:                      index=["a", "c", "e"],
   ....:                      columns=["Ohio", "Nevada"]).astype("Int64")

In [103]:
right2 = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13,14]],
                      index =["b","c","d","e"],
                      columns=["Missouri","Alabama"]).astype("Int64")

In [104]:
left2

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [105]:
right2

   Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [106]:
pd.merge(left2,right2, how="outer", left_index = True , right_index=True)

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [107]:
left2.join(right2, how="outer")

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [108]:
left1.join(right1, on="key")

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [109]:
#think of this method as joining "into" the object whose join method was called

In [110]:
#for index-on-index merges

In [111]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
   ....:                        index=["a", "c", "e", "f"],
   ....:                        columns=["New York", "Oregon"])

In [112]:
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [113]:
left2.join([right2 , another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [114]:
left2.join([right2, another], how = "outer")

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
b  <NA>    <NA>         7        8       NaN     NaN
c     3       4         9       10       9.0    10.0
d  <NA>    <NA>        11       12       NaN     NaN
e     5       6        13       14      11.0    12.0
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0

In [115]:
left2

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [116]:
right2

   Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [117]:
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [118]:
#here i am recalling all the functions so that i can see whether the data is correct or not !

**Concatinating along an axis

In [119]:
#also known as stacking because we are literally STACKING up data here!!

In [120]:
#using numpy concatenate function

In [121]:
dw = np.arange(12).reshape((3,4))

In [122]:
dw

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
np.concatenate([dw, dw] , axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [124]:
#here we defined the axis = 1 and concatenated dw we can also do it for axis = 0

In [125]:
np.concatenate([dw,dw], axis =0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
s1 =  pd.Series([0, 1], index=["a", "b"], dtype="Int64")

In [127]:
s2 = pd.Series([2,3,4], index=["c","d","e"], dtype="Int64")

In [128]:
s3 = pd.Series([5,6], index=["f","g"], dtype="Int64")

In [129]:
s1

a    0
b    1
dtype: Int64

In [130]:
s2

c    2
d    3
e    4
dtype: Int64

In [131]:
s3

f    5
g    6
dtype: Int64

In [132]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [133]:
#here the concat default is to use axis="index" which gave us another series suppose we want the data in form of dataframe for that :

In [134]:
#concatination in form of dataframe

In [135]:
pd.concat([s1,s2,s3], axis="columns")

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [136]:
#here this is in the form of UNION i.e. the "outer" join of the indexes

In [137]:
#for intersecting use join = "inner"

In [138]:
pd.concat([s1,s2,s3], axis="columns", join="inner")

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [139]:
s4 = pd.concat([s1,s3])

In [140]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [141]:
pd.concat([s1,s4] , axis="columns")

      0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [142]:
pd.concat([s1,s4] , axis="columns", join="inner")
#this one is intersection method that is why f and g are removed .

   0  1
a  0  0
b  1  1

In [143]:
#what if i wanted to create hierarchical index on the concatenation axis

In [144]:
result = pd.concat([s1,s2,s3], keys=["one","two","three"])

In [145]:
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: Int64

In [146]:
#what if we just play around and use the axis as columns just an intrusive thought

In [147]:
result1 = pd.concat([s1,s2,s3], keys=["one","two","three"], axis = "columns")

In [148]:
result1
#here nothing much changed the only thing that changed is the labels on axis 1 
#again it was just an experiment i wanted to know what will happen if i just changed the axis

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [149]:
result.unstack() #here for axis = "index" 
#one pattern to notice is that when we stack along index axis we get a hierarchial series meanwhile when 
#we unstack it , it becomes a dataframe and the vice versa happens with axis = "columns"

          a     b     c     d     e     f     g
one       0     1  <NA>  <NA>  <NA>  <NA>  <NA>
two    <NA>  <NA>     2     3     4  <NA>  <NA>
three  <NA>  <NA>  <NA>  <NA>  <NA>     5     6

In [150]:
result1.unstack()

one    a       0
       b       1
       c    <NA>
       d    <NA>
       e    <NA>
       f    <NA>
       g    <NA>
two    a    <NA>
       b    <NA>
       c       2
       d       3
       e       4
       f    <NA>
       g    <NA>
three  a    <NA>
       b    <NA>
       c    <NA>
       d    <NA>
       e    <NA>
       f       5
       g       6
dtype: Int64

In [151]:
#now what if the object is dataframe

In [152]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2), index = ["a", "b", "c"],
   .....:                    columns=["one", "two"])

In [153]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=["a", "c"],
   .....:                    columns=["three", "four"])

In [154]:
pd.concat([df1,df2])
#the axis here is default as index axis and a dataframe

   one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN    5.0   6.0
c  NaN  NaN    7.0   8.0

In [155]:
pd.concat([df1, df2], axis="columns")

   one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [156]:
pd.concat([df1, df2], axis="columns", keys=["level1", "level2"])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [157]:
# here why to use keys? 
#just in case the data is too noisy(which happens a lot in real world applications) so to create a hierarchy we used the keys

In [158]:
#if you pass a dictionary
pd.concat([df1,df2], axis="columns", keys=["level1", "level2"],
          names = ["upper", "lower"])

upper level1     level2
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [159]:
# #for DataFrames in which the row index does not contain
# any relevant data:

In [160]:
df1 = pd.DataFrame(np.random.standard_normal((3, 4)),
   .....:                    columns=["a", "b", "c", "d"])

In [161]:
df2 = pd.DataFrame(np.random.standard_normal((2,3)), 
                   columns=["b", "d", "a"])

In [162]:
df1

          a         b         c         d
0 -0.802012 -0.366944  1.770774 -1.044075
1 -0.402813  0.531720 -0.520833 -0.417203
2  0.508165  0.405711 -0.122856 -0.305305

In [163]:
df2

          b         d         a
0  0.017206  0.882941 -1.882753
1 -2.481564 -0.529475  0.698732

In [164]:
pd.concat([df1, df2], ignore_index=True)

          a         b         c         d
0 -0.802012 -0.366944  1.770774 -1.044075
1 -0.402813  0.531720 -0.520833 -0.417203
2  0.508165  0.405711 -0.122856 -0.305305
3 -1.882753  0.017206       NaN  0.882941
4  0.698732 -2.481564       NaN -0.529475

In [165]:
# #as row index doesn't contains any relevant data so we just used the ignore_index=True that discards the indexes
# from each df and concat the data in columns only creating a new default index

**Combining Data with Overlap**

In [166]:
#data combination situations that can't be expressed as either a merge or concatenation operation

In [167]:
#eg:
a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
              index = ["f", "e", "d", "c", "b", "a"])

In [168]:
b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
.....:               
index=["a", "b", "c", "d", "e", "f"])

In [169]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [170]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [171]:
np.where(pd.isna(a),b,a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [172]:
# #Here, whenever values in a are null, values from b are selected, otherwise the non
# null values from a are selected.

In [173]:
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [174]:
#its doing the samething as np.where but its just replacing the NAN values with the values from b

In [175]:
df1 = pd.DataFrame({"a": [1., np.nan, 5., np.nan],                    
"b": [np.nan, 2., np.nan, 6.],
"c": range(2, 18, 4)})

In [176]:
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
.....:                     
"b": [np.nan, 3., 4., 6., 8.]})

In [177]:
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [178]:
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [179]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [180]:
#just like in series we can see the same operation goes in dataframe also that is the union of both the dataframes in this case

In [181]:
#this section ends here

In [182]:
#Summary is: if a series or dataframe is A  and another is B and if A = NaN then we borrow from B

## Reshaping and Pivoting (Finale Part)

**Reshaping with hierarchical indexing

In [183]:
#two ways to do it first stack and other unstack :
#Stack: pivots columns to rows
#Unstack: pivots rows to columns

In [184]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
   .....:                     index=pd.Index(["Ohio", "Colorado"], name="state"),
   .....:                     columns=pd.Index(["one", "two", "three"],
   .....:                     name="number"))

In [185]:
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [186]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [187]:
#here the dataframe is pivoted into rows producing a series

In [188]:
#converting this series back to dataframe
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [189]:
#to unstack a different level by passing a level number or name
result.unstack(level=0)

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [190]:
result.unstack(level=1)

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [191]:
#using name
result.unstack("state")

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [192]:
result.unstack("number")

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [193]:
# Unstacking might introduce missing data if all of the values in the level aren’t found
# in each subgroup

In [194]:
S1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")

In [195]:
S2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")

In [196]:
S1

a    0
b    1
c    2
d    3
dtype: Int64

In [197]:
S2

c    4
d    5
e    6
dtype: Int64

In [198]:
data2 = pd.concat([S1,S2], keys=["one","two"])

In [199]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [200]:
#Stacking filters out missing data by default so the ops is invertible

In [201]:
data2.unstack()

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [202]:
data2.unstack().stack() #here drona = False by default and also the material i am using is bit old *2022* so that is why due to major changes in pandas it might show error if u use:
#data2.unstack().stack(dropna=False)

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [203]:
#When you unstack in a DataFrame, the level unstacked becomes the lowest level in
# the result

In [204]:
df = pd.DataFrame({"left": result, "right":result + 5}, columns=pd.Index(["left","right"], name="side"))

In [205]:
df

side             left  right
state    number
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [206]:
df.unstack(level="state")

side   left          right
state  Ohio Colorado  Ohio Colorado
number
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [207]:
df.unstack(level="state").stack(level="side")

state         Ohio  Colorado
number side
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

**Pivoting “Long” to “Wide” Format

In [208]:
#In long or stack format individual values are represented by a single row in a table rathen than multiple values per row

In [225]:
L = pd.DataFrame({
    'student': ['Alice','Alice','Bob','Bob'],
    'subject': ['Math','English','Math','English'],
    'score':   [90, 85, 72, 88]
})

In [226]:
L

  student  subject  score
0   Alice     Math     90
1   Alice  English     85
2     Bob     Math     72
3     Bob  English     88

In [234]:
wide = L.pivot(
    index='student',    # stays as rows
    columns='subject',  # values → column headers
    values='score'      # fills the cells
)

In [235]:
wide

subject  English  Math
student
Alice         85    90
Bob           88    72

In [236]:
wide.reset_index(inplace=True)

In [237]:
wide

subject student  English  Math
0         Alice       85    90
1           Bob       88    72

In [239]:
wide.columns.name = None #cleaning up the names

In [240]:
wide

  student  English  Math
0   Alice       85    90
1     Bob       88    72

In [241]:
#aggregate duplicates

In [242]:
wide = L.pivot_table(
    index='student',
    columns='subject',
    values='score',
    aggfunc='mean'   # 'sum', 'max', 'count', etc.
).reset_index()

In [243]:
wide

subject student  English  Math
0         Alice     85.0  90.0
1           Bob     88.0  72.0

**Pivoting “Wide” to “Long” Format

In [244]:
#we use pandas.melt here to merge multiple columns into one

In [245]:
Lf = pd.DataFrame({"key": ["foo", "bar", "baz"],
                           "A": [1, 2, 3],
                   "B": [4,5,6],
                   "C": [7,8,9]})

In [246]:
Lf

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [247]:
#When using pandas.melt, we must indicate which columns (if any) are group indicators

In [252]:
melt = pd.melt(Lf, id_vars = "key")  
#here note that id_vars is a argument (parameter) of the function pd.melt() 
#id_vars

# stands for:

# identifier variables

# Meaning:

# columns that should stay as identifiers and should NOT be melted

In [253]:
melt

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [257]:
#reshaping it back to the original one
reshaped = melt.pivot(index="key",columns="variable",values="value")

In [258]:
reshaped

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [259]:
#using reset_index to move the data back into a column

In [260]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [261]:
#we can also specify a subset of columns to use as value columns

In [263]:
pd.melt(Lf, id_vars="key", value_vars=["A", "B"])

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [264]:
#pd.melts can be used without any identifiers

In [265]:
 pd.melt(Lf, value_vars=["A", "B", "C"])

  variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [267]:
pd.melt(Lf, value_vars=["key", "A", "B"])

  variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6

In [ ]:
##THE END !!