In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

In [4]:
obj = pd.Series([3,4,5,6])

In [5]:
obj

0    3
1    4
2    5
3    6
dtype: int64

In [6]:
obj[3]

np.int64(6)

In [7]:
obj.array

<NumpyExtensionArray>
[3, 4, 5, 6]
Length: 4, dtype: int64

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='str')

In [12]:
obj2["d"]

np.int64(4)

In [13]:
obj2["d"] = 6

In [14]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [15]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [16]:
#NOTE HERE ["c", "a", "d"] THIS IS A LIST even though isme strings hai instead of integers

In [17]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
#notice one more thing here , its not a VIEW its a whole new copy of the original wwith changes that is the original thing is being copied and used again

In [20]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [21]:
"b" in obj2

True

In [22]:
"e" in obj2

False

In [23]:
 sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [24]:
obj3 = pd.Series(sdata)

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
#for converting series to dictionary":
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [27]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [28]:
obj4 = pd.Series(sdata, index=states)

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [32]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
obj4.notna()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [34]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [35]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [36]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [37]:
obj4.name = "Population"

In [38]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Population, dtype: float64

In [39]:
obj4.index.name = "state"

In [40]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Population, dtype: float64

In [41]:
obj

0    3
1    4
2    5
3    6
dtype: int64

In [42]:
 obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [43]:
obj

Bob      3
Steve    4
Jeff     5
Ryan     6
dtype: int64

In [44]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [45]:
frame = pd.DataFrame(data)

In [46]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [47]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [48]:
 pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [49]:
 pd.DataFrame(data, columns=["year", "state", "pop", "cornhub"])

   year   state  pop cornhub
0  2000    Ohio  1.5     NaN
1  2001    Ohio  1.7     NaN
2  2002    Ohio  3.6     NaN
3  2001  Nevada  2.4     NaN
4  2002  Nevada  2.9     NaN
5  2003  Nevada  3.2     NaN

In [50]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [51]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [53]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [54]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [55]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [56]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [57]:
frame2.loc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [58]:
frame2["debt"] = 16.5

In [59]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [60]:
frame2["debt"] = np.arange(6.)

In [61]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [62]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [63]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [64]:
frame2["debt"] = val

In [65]:
frame2
#here in the output why there is NaN? because the values length must  match the length of the data fram3e which is not happening here

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [66]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [67]:
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [68]:
del frame2["eastern"]

In [69]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [70]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [71]:
populations = {"Ohio":{2000:1.5, 2001:1.7, 2002: 3.6}, "Nevada":{2001: 2.4, 2002:2.9}}

In [72]:
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [73]:
frame3 = pd.DataFrame(populations)

In [74]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [75]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [76]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [77]:
pdata = {"Ohio": frame3["Ohio"][:-1],
....:          
"Nevada": frame3["Nevada"][:2]}

In [78]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64,
 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [79]:
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [80]:
frame3.index.name = "year"

In [81]:
frame3

      Ohio  Nevada
year
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [82]:
frame3.columns.name = "States"

In [83]:
frame3

States  Ohio  Nevada
year
2000     1.5     NaN
2001     1.7     2.4
2002     3.6     2.9

In [84]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [85]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [86]:
obj = pd.Series(np.arange(3), index = ["a", "b", "c"])

In [87]:
obj

a    0
b    1
c    2
dtype: int64

In [88]:
index = obj.index

In [89]:
index

Index(['a', 'b', 'c'], dtype='str')

In [90]:
index[1:]

Index(['b', 'c'], dtype='str')

In [91]:
# index[1] = "d" 
# #TYPERROR BECAUSE INDEX OBJECTS ARE IMMUATABLE

In [92]:
labels = pd.Index(np.arange(3))

In [93]:
labels

Index([0, 1, 2], dtype='int64')

In [94]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [95]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [96]:
obj2.index is labels

True

In [97]:
frame3

States  Ohio  Nevada
year
2000     1.5     NaN
2001     1.7     2.4
2002     3.6     2.9

In [98]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='str', name='States')

In [99]:
 "Ohio" in frame3.columns

True

In [100]:
2003 in frame3.index

False

In [101]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')

In [102]:
frame3

States  Ohio  Nevada
year
2000     1.5     NaN
2001     1.7     2.4
2002     3.6     2.9

** Reindexing

In [103]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [104]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [105]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [106]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [107]:
obj3 = pd.Series(["blue", "black", "white"], index=[0,2,4])

In [108]:
obj3

0     blue
2    black
4    white
dtype: str

In [109]:
obj3.reindex(np.arange(6), method ="ffill")  #for ordered data we use "method" method then ffill to get time series in pandas

0     blue
1     blue
2    black
3    black
4    white
5    white
dtype: str

In [110]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ["a" , "c", "d"], columns = ["Ohio", "Texas", "California"])

In [111]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [112]:
# INDEX = ROWS ,

In [113]:
frame2 = frame.reindex(index = ["a" , "b", "c", "d"])

In [114]:
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [115]:
#idhar dhyan do while reindexing in dataframe we are creating a new df insteading of modifying the old one that implies that
#we are copying whole data instead of just viewing it !!!

In [116]:
 states = ["Texas", "Utah", "California"]

In [117]:
frame.reindex(columns = states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [118]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [119]:
series = ["gareeb" , "gareeb pro", "gareebb pro max "]

In [120]:
frame.reindex(index = series)

                  Ohio  Texas  California
gareeb             NaN    NaN         NaN
gareeb pro         NaN    NaN         NaN
gareebb pro max    NaN    NaN         NaN

In [121]:
#another thing to notice either we can create a row or coloumn with new name and then reindex in the "fram" here or just 
#use the prior method that is creating entire new DF that is "frame2" here

In [122]:
frame.loc[["a","d","c"] , ["California","Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

**Dropping Entries from an Axis

In [123]:
obj = pd.Series(np.arange(5.), index = ["a", "b", "c", "d" , "e"])

In [124]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [125]:
new_obj = obj.drop("c")

In [126]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [127]:
obj.drop(["a","b"])

c    2.0
d    3.0
e    4.0
dtype: float64

In [128]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
.....:                     
.....:                     
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])

In [129]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [130]:
data.drop(index = ["Ohio", "Utah"])

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [131]:
data.drop(columns = ["two","three"])

          one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

In [132]:
data.drop(index = ["Ohio","Utah"] , columns = ["one"])

          two  three  four
Colorado    5      6     7
New York   13     14    15

In [133]:
#or another method to do it is : 
data.drop("two", axis = 1 )

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [134]:
data.drop(["Ohio", "Utah"] , axis = 0)

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [135]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
obj = pd.Series(np.arange(4), index = ["a","b","c","d"])

In [137]:
obj

a    0
b    1
c    2
d    3
dtype: int64

In [138]:
obj["d"]

np.int64(3)

In [139]:
obj[2:3]

c    2
dtype: int64

In [140]:
obj[1:3]

b    1
c    2
dtype: int64

In [141]:
obj[["a","d","b"]]  #we use double brackets because we need to make it a list for more then one values

a    0
d    3
b    1
dtype: int64

In [142]:
obj.loc[["b", "a", "d"]]

b    1
a    0
d    3
dtype: int64

In [143]:
 obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [144]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [145]:
obj1

2    1
0    2
1    3
dtype: int64

In [146]:
obj2

a    1
b    2
c    3
dtype: int64

In [147]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [148]:
obj2[["a", "b", "c"]]

a    1
b    2
c    3
dtype: int64

In [149]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [150]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [151]:
 obj2.loc["b":"c"] = 5

In [152]:
obj2

a    1
b    5
c    5
dtype: int64

In [153]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
.....:                     
.....:                     
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])

In [154]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [155]:
 data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [156]:
data[["two","three"]]

          two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [157]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [158]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [159]:
data[data<5] = 0

In [160]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data[data>5] = 1

In [162]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      1     1
Utah        1    1      1     1
New York    1    1      1     1

In [163]:
data.loc["Colorado"]

one      0
two      5
three    1
four     1
Name: Colorado, dtype: int64

In [164]:
data.loc[["Ohio","Utah"]]

      one  two  three  four
Ohio    0    0      0     0
Utah    1    1      1     1

In [165]:
data.loc["Ohio",["two" , "three"]]

two      0
three    0
Name: Ohio, dtype: int64

In [166]:
data.iloc[2]

one      1
two      1
three    1
four     1
Name: Utah, dtype: int64

In [167]:
data.iloc[[2,1]]

          one  two  three  four
Utah        1    1      1     1
Colorado    0    5      1     1

In [168]:
data.iloc[2,[3,0,1]]

four    1
one     1
two     1
Name: Utah, dtype: int64

In [169]:
data.iloc[[2,3],[3,0,1]]

          four  one  two
Utah         1    1    1
New York     1    1    1

In [170]:
 data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        1
Name: two, dtype: int64

In [171]:
 data.iloc[:, :3][data.three > 5]

Empty DataFrame
Columns: [one, two, three]
Index: []

In [172]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      1     1
Utah        1    1      1     1
New York    1    1      1     1

In [173]:
data.loc[data.three >= 2]

Empty DataFrame
Columns: [one, two, three, four]
Index: []

In [174]:
ser = pd.Series(np.arange(3.))

In [175]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [176]:
# ser[-1] this will give error because panda would fall back here becaues its confused and does not want to guess what the user wants like label based indexing or integer based KYUKNI IDHAR INDEX BHI INTEGER MEIN HAI ISILYE

In [177]:
#counter example
ser2 = pd.Series(np.arange(3.) , index = ["a" , "b" , "c"])

In [178]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [179]:
ser2.iloc[-1]

np.float64(2.0)

In [180]:
#KYA SEEKHA? AISI AMBIGUITIES SE BACHNE KE LIYE THAT IS FALTU KA ERROR WHILE INDEXING SE BACHNE KE LIYE ITS BETTER TO USE 
#ILOC AND LOC for inexing dawg

**PITFALLS WITH CHAIN INDEXING

In [181]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      1     1
Utah        1    1      1     1
New York    1    1      1     1

In [182]:
data2 = pd.DataFrame(np.arange(16).reshape((4,4)) ,index = ["Ohio", "Colorado", "Utah", "New York"] , columns=["one", "two", "three", "four"])

In [183]:
data2

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [184]:
data2.loc[:, "one"] = 1  # empy : means all rows

In [185]:
data2

          one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [186]:
data2.iloc[2] = 56

In [187]:
data2

          one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah       56   56     56    56
New York    1   13     14    15

In [188]:
data2.iloc[2,2] = 69

In [189]:
data2

          one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah       56   56     69    56
New York    1   13     14    15

In [190]:
data2.loc[data2["four"]>5] = 2

In [191]:
data2

          one  two  three  four
Ohio        1    1      2     3
Colorado    2    2      2     2
Utah        2    2      2     2
New York    2    2      2     2

In [192]:
data2.loc[data.three == 5, "three"] = 6

In [193]:
data2

          one  two  three  four
Ohio        1    1      2     3
Colorado    2    2      2     2
Utah        2    2      2     2
New York    2    2      2     2

In [194]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

In [195]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
.....:                
index=["a", "c", "e", "f", "g"])

In [196]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [197]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [198]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [199]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns = list("bcd") , index = ["Utah", "Ohio","Texas"])

In [200]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list("bde"), index = ["Utah", "Ohio", "Texas", "Oregon"])

In [201]:
df1 + df2

           b   c     d   e
Ohio     6.0 NaN   9.0 NaN
Oregon   NaN NaN   NaN NaN
Texas   12.0 NaN  15.0 NaN
Utah     0.0 NaN   3.0 NaN

In [202]:
# #Since the "c" and "e" columns are not found in both DataFrame objects, they appear
# as missing in the result. The same holds for the rows with labels that are not common
# to both objects

In [203]:
 df1 = pd.DataFrame({"A": [1, 2]})

In [204]:
df2 = pd.DataFrame({"B": [3,4]})

In [205]:
df1 + df2

    A   B
0 NaN NaN
1 NaN NaN

In [206]:
#NO COLUMNS OR ROWS COMMON SO NULL

In [207]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)), 
                   columns=list("abcd"))

In [208]:
df1

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [209]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
   .....:                    columns=list("abcde"))

In [210]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [211]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [212]:
df1.add(df2, fill_value = 0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [213]:
1/df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [214]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [215]:
df1.reindex(columns=df2.columns, fill_value=0)

   a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [216]:
import numpy as np

In [217]:
arr = np.arange(12.).reshape((3,4))

In [218]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [219]:
arr[0]

array([0., 1., 2., 3.])

In [220]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [221]:
import pandas as pd

In [222]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
   .....:                      columns=list("bde"),
   .....:                      index=["Utah", "Ohio", "Texas", "Oregon"])

In [223]:
series = frame.iloc[0]

In [224]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [225]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [226]:
series + frame

          b     d     e
Utah    0.0   2.0   4.0
Ohio    3.0   5.0   7.0
Texas   6.0   8.0  10.0
Oregon  9.0  11.0  13.0

In [227]:
series2 = pd.DataFrame(np.arange(3), index = ["b","d","f"])

In [228]:
series2

   0
b  0
d  1
f  2

In [229]:
series2 + frame

         0   b   d   e
Ohio   NaN NaN NaN NaN
Oregon NaN NaN NaN NaN
Texas  NaN NaN NaN NaN
Utah   NaN NaN NaN NaN
b      NaN NaN NaN NaN
d      NaN NaN NaN NaN
f      NaN NaN NaN NaN

In [230]:
series3 = frame["d"]

In [231]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [232]:
frame.sub(series3, axis = "index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [233]:
frame.sub(series3, axis = "columns")

        Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

** FUNCTION APPLICATION AND MAPPING

In [234]:
frame = pd.DataFrame(np.random.standard_normal((4,3)), columns =list("bde"), index = ["Utah", "Ohio", "Texas", "Oregon"])

In [235]:
frame

               b         d         e
Utah    0.086700  0.337460  1.383770
Ohio    1.027056 -0.605571 -0.659601
Texas  -0.956482  0.124296  0.382857
Oregon -0.390545 -0.210520  0.698851

In [236]:
np.abs(frame)

               b         d         e
Utah    0.086700  0.337460  1.383770
Ohio    1.027056  0.605571  0.659601
Texas   0.956482  0.124296  0.382857
Oregon  0.390545  0.210520  0.698851

In [237]:
def f1(x):
    return x.max() - x.min()

In [238]:
frame.apply(f1)

b    1.983537
d    0.943031
e    2.043370
dtype: float64

In [239]:
#apply across the column
frame.apply(f1, axis = "columns")

Utah      1.297069
Ohio      1.686656
Texas     1.339338
Oregon    1.089397
dtype: float64

In [240]:
def f2(x): return pd.Series([x.min(), x.max()], index=["min", "max"])

In [241]:
frame.apply(f2, axis = "index")

            b         d         e
min -0.956482 -0.605571 -0.659601
max  1.027056  0.337460  1.383770

In [242]:
frame

               b         d         e
Utah    0.086700  0.337460  1.383770
Ohio    1.027056 -0.605571 -0.659601
Texas  -0.956482  0.124296  0.382857
Oregon -0.390545 -0.210520  0.698851

In [243]:
def my_format(x):     return f"{x:.2f}"

In [244]:
frame.map(my_format) #applymap has been replaced with just map

            b      d      e
Utah     0.09   0.34   1.38
Ohio     1.03  -0.61  -0.66
Texas   -0.96   0.12   0.38
Oregon  -0.39  -0.21   0.70

In [245]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [246]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [247]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [248]:
 frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=["three", "one"], columns=["d", "a", "b", "c"])

In [249]:
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [250]:
frame.sort_index(axis = "index")

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [251]:
frame.sort_index(axis = "columns") #here for default it is in ascending order but we can also make it descending)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [252]:
frame.sort_index(axis = "columns", ascending = False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [253]:
ser = pd.Series(np.arange(8), index = list("abcdefgh"))

In [254]:
ser

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [255]:
ser.sort_values()

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [256]:
ser.sort_values(ascending = False)

h    7
g    6
f    5
e    4
d    3
c    2
b    1
a    0
dtype: int64

In [257]:
#any missing values are sorted at the end of the series by default

In [258]:
obj = pd.Series([4, np.nan, 7, 8, np.nan])

In [259]:
obj

0    4.0
1    NaN
2    7.0
3    8.0
4    NaN
dtype: float64

In [260]:
obj.sort_values()

0    4.0
2    7.0
3    8.0
1    NaN
4    NaN
dtype: float64

In [261]:
obj.sort_values(ascending = False)

3    8.0
2    7.0
0    4.0
1    NaN
4    NaN
dtype: float64

In [262]:
#kya seekha? no matter the order ascending or descending the NaN type value will always be the last

In [263]:
obj.sort_values(na_position = "first")

1    NaN
4    NaN
0    4.0
2    7.0
3    8.0
dtype: float64

In [264]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [265]:
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [266]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [267]:
frame.sort_values(["a", "b"], ascending = False)

   b  a
1  7  1
3  2  1
0  4  0
2 -3  0

*RANKING

In [268]:
import pandas as pd

In [269]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4], index = list("abcdefg"))

In [270]:
obj

a    7
b   -5
c    7
d    4
e    2
f    0
g    4
dtype: int64

In [271]:
obj.rank(ascending = False)

a    1.5
b    7.0
c    1.5
d    3.5
e    5.0
f    6.0
g    3.5
dtype: float64

In [272]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
   .....:                       "c": [-2, 5, 8, -2.5]})

In [273]:
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [274]:
frame.rank(axis = "columns" , ascending = False)

     b    a    c
0  1.0  2.0  3.0
1  1.0  3.0  2.0
2  3.0  2.0  1.0
3  1.0  2.0  3.0

In [275]:
frame.rank(axis = "index", ascending= False)

     b    a    c
0  2.0  3.5  3.0
1  1.0  1.5  2.0
2  4.0  3.5  1.0
3  3.0  1.5  4.0

In [276]:
frame.rank(method = "min")

     b    a    c
0  3.0  1.0  2.0
1  4.0  3.0  3.0
2  1.0  1.0  4.0
3  2.0  3.0  1.0

In [277]:
frame.rank(method = "first")

     b    a    c
0  3.0  1.0  2.0
1  4.0  3.0  3.0
2  1.0  2.0  4.0
3  2.0  4.0  1.0

In [278]:
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

    **Axis Indexes with Duplicate Labels

In [279]:
obj =  pd.Series(np.arange(5), index = ["a", "a", "b", "b", "c"])

In [280]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [281]:
obj.index.is_unique

False

In [282]:
obj["a"]

a    0
a    1
dtype: int64

In [283]:
obj["b"]

b    2
b    3
dtype: int64

In [284]:
obj["c"]

np.int64(4)

In [285]:
df = pd.DataFrame(np.random.standard_normal((5,3)), index = ["a","a","b","b","c"])

In [286]:
df

          0         1         2
a -2.101029  1.891472 -1.412373
a  0.337083 -0.220692  0.340175
b  1.369861  0.800464 -0.569487
b -0.432889 -0.109863  0.028595
c -0.923803 -0.967599  0.637067

In [287]:
df.loc["b"]

          0         1         2
b  1.369861  0.800464 -0.569487
b -0.432889 -0.109863  0.028595

In [288]:
df.loc["c"]

0   -0.923803
1   -0.967599
2    0.637067
Name: c, dtype: float64

In [289]:
#done !!

##  Summarizing and Computing Descriptive Statistics

In [290]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
   .....:                    [np.nan, np.nan], [0.75, -1.3]],
   .....:                   index=["a", "b", "c", "d"],
   .....:                   columns=["one", "two"])

In [291]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [292]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [293]:
df.sum(axis = "columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [294]:
df.sum(axis = "rows")

one    9.25
two   -5.80
dtype: float64

In [295]:
 df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [296]:
df.sum(axis="columns", skipna=False)
#Do NOT ignore NaN values skipna = False ka mtlb icch yhi hota hai

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [297]:
 df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [298]:
df.mean(axis="index")

one    3.083333
two   -2.900000
dtype: float64

In [299]:
df.idxmax()

one    b
two    d
dtype: str

In [300]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [301]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [302]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [303]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: str

In [304]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [305]:
obj.cumsum()

0                    a
1                   aa
2                  aab
3                 aabc
4                aabca
5               aabcaa
6              aabcaab
7             aabcaabc
8            aabcaabca
9           aabcaabcaa
10         aabcaabcaab
11        aabcaabcaabc
12       aabcaabcaabca
13      aabcaabcaabcaa
14     aabcaabcaabcaab
15    aabcaabcaabcaabc
dtype: str

In [306]:
 obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [307]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [308]:
uniques = obj.unique()

In [309]:
uniques

<StringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

In [310]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [313]:
pd.Series(obj.to_numpy()).value_counts(sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [314]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [315]:
pd.Series(obj.to_numpy()).value_counts(sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [316]:
mask = obj.isin(["b","c","d"])

In [317]:
mask

0     True
1    False
2     True
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [318]:
obj[mask] #lists of masked objects in the series

0    c
2    d
5    b
6    b
7    c
8    c
dtype: str

In [319]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [320]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: str

In [321]:
unique_vals = pd.Series(["c", "b", "a"])

In [322]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [323]:
indices

array([0, 2, 1, 1, 0, 2])

In [324]:
 data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                       "Qu2": [2, 3, 1, 2, 3],"Qu3": [1, 5, 2, 4, 4]})

In [325]:
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [326]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [328]:
result = data.apply(lambda x: x.value_counts()).fillna(0)

In [329]:
result

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [ ]:
#exit chapter completed !!